# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-05 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaselineProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='profiles')),
            ],
            options={
                'db_table': 'profile',
            },
        ),
    ]
