# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-06 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('omniproapp', '0002_auto_20161205_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaselineProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='documents/%Y%m%d')),
            ],
        ),
    ]
