# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-06 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omniproapp', '0003_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasuredProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_file', models.FileField(null=True, upload_to='measurements/%Y%m%d')),
            ],
        ),
        migrations.RemoveField(
            model_name='baselineprofile',
            name='docfile',
        ),
        migrations.AddField(
            model_name='baselineprofile',
            name='baseline_file',
            field=models.FileField(null=True, upload_to='baselines/%Y%m%d'),
        ),
    ]
