# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-06 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omniproapp', '0004_auto_20161206_0925'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BaselineProfile',
            new_name='BaselineProfileModel',
        ),
        migrations.RenameModel(
            old_name='MeasuredProfile',
            new_name='MeasuredProfileModel',
        ),
    ]
